[project]
name = "ironhack-week-1-vikings"
version = "0.1.0"
description = "War simulation project for Ironhack Bootcamp"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.uv]
package = true
